In [18]:
import torch
x = torch.randn(1, 3, 6)
x

tensor([[[-0.4559, -1.6886,  0.5308,  2.2056, -1.4222, -0.6954],
         [-0.9683,  0.7831,  1.4345, -1.5872, -0.5417,  0.1998],
         [-0.8650, -1.4079,  0.4849,  1.5751,  0.5243, -0.2936]]])

In [19]:
x = x.softmax(dim=1)
x_sorted, indices = torch.sort(x, dim=1, descending=True)
x

tensor([[[0.4418, 0.0706, 0.2260, 0.6431, 0.0960, 0.2023],
         [0.2647, 0.8360, 0.5580, 0.0145, 0.2316, 0.4953],
         [0.2935, 0.0935, 0.2159, 0.3424, 0.6724, 0.3024]]])

In [20]:
x_sorted

tensor([[[0.4418, 0.8360, 0.5580, 0.6431, 0.6724, 0.4953],
         [0.2935, 0.0935, 0.2260, 0.3424, 0.2316, 0.3024],
         [0.2647, 0.0706, 0.2159, 0.0145, 0.0960, 0.2023]]])

In [21]:
indices

tensor([[[0, 1, 1, 0, 2, 1],
         [2, 2, 0, 2, 1, 2],
         [1, 0, 2, 1, 0, 0]]])

In [22]:
weights = torch.logspace(start=0, end=3-1, steps=3, base=0.9).unsqueeze(-1)
weighted_sorted = x_sorted * weights.to(x.device)

In [23]:
weighted_sorted

tensor([[[0.4418, 0.8360, 0.5580, 0.6431, 0.6724, 0.4953],
         [0.2641, 0.0841, 0.2034, 0.3081, 0.2084, 0.2722],
         [0.2144, 0.0572, 0.1749, 0.0117, 0.0778, 0.1639]]])

In [24]:
result = torch.empty_like(x)
inv_indices = indices.argsort(dim=1)
result.scatter_(1, inv_indices, weighted_sorted)

tensor([[[0.4418, 0.0841, 0.2034, 0.6431, 0.0778, 0.2722],
         [0.2144, 0.0572, 0.5580, 0.0117, 0.2084, 0.1639],
         [0.2641, 0.8360, 0.1749, 0.3081, 0.6724, 0.4953]]])

In [2]:
list_path = 'val_id'
train = 'train' in list_path
train

False